### PR TITLE
feat(providers): add posthog support

### PR DESCRIPTION
**Pull request by morigs**
## This PR

Add provider for PostHog.
It also adds go workspace because gopls doesn't work properly in multi-module repos without it.

### Related Issues

?

### Notes

Not yet added:
- Tests
- Examples
- Readme

### CODE REVIEW

**Comment by beeme1mr** [comment]
Hey @morigs, thanks for the PR. I've kicked off the CI and it looks like the tests are failing. Would you mind taking a look when you have a moment?

**Comment by beeme1mr** [comment]
Ah, sorry. I see you have this PR marked as a draft. Ping me if you need anything!

**Comment by morigs** [comment]
Yeah, sorry, unfortunately, I don't have time to finish this now :(
I hope to return to this someday

**Comment by beeme1mr** [comment]
Closing for now due to inactivity.

**Pull request closed without merging**
