### PR TITLE
feat: otel hook error status override option

### LINKED ISSUE #208: feat: option to override otel hook behavior
**Background**

With https://github.com/open-feature/go-sdk-contrib/issues/204, errors will set the span state to `Error`. However, a user might need to disable this behavior (ex:- as span is shared with logic other than flag evaluation). 

**Expected output**

Provide an option to disable the span error state.

### PR DESCRIPTION
**Pull request by Kavindu-Dodan**
## This PR

Fixes #208

This PR introduces hook build option `WithErrorStatusEnabled`. 

From README,

> **WithErrorStatusEnabled** : enable setting span status to `Error` in case of an error. Default behavior is disabled, 
  span status is unset for errors.

Code example

```
openfeature.AddHooks(
   otelhooks.NewHook(hooks.WithErrorStatusEnabled()))
```

This gives end-user the control over hook behavior

### CODE REVIEW

**Comment by toddbaert** [comment]
@thisthat had some opinions about this (which mode should be the default). Personally I'm fine with marking the span as an error by default, but I'd like to come to an agreement, because we should be consistent with all implementations. I'm also not an OTel expert by any stretch.

cc @bacherfl @beeme1mr @thisthat

**Comment by thisthat** [comment]
There are arguments for both directions. I suggest recording an OpenFeature error because a FF evaluation constitutes an exception that is internally handled and does not impact the "client request". Marking the Span (and consequentially the whole trace) as an error could potentially trigger alerts on the Observability platform used to ingest traces.

From the [OTel spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-status) they say the following

> Analysis tools SHOULD respond to an Ok status by suppressing any errors they would otherwise generate. For example, to suppress noisy errors such as 404s.

I would consider a FF evaluation under this category. 
Nevertheless, OTel also has some recommendations handy-dandy APIs to record exception, which fit our use case imho: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/exceptions.md#recording-an-exception

Since the internal OF error is never pushed to the user, I would suggest recording the event with `exception.escaped = false`. The SDK should already handle all the remaining properties (see https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/trace/span.go#L427)

**Comment by Kavindu-Dodan** [comment]
@thisthat  thank you for the review and references.

The current hook implementation performs the error recording [1]. And the newest change here was to set the status to `Error`.

This PR gives the end user the **option** to **disable** setting the Span status to `Error`. And this could help them with error suppression if that's the desired behavior. 

So can we agree on the following, 

- Hook will record & by default set the status to `Error` for OpenFeature errors
- Hook will provide configurability to disable the status setting behavior (i.e - disable setting Span status to `Error`)


[1] - https://github.com/open-feature/go-sdk-contrib/blob/main/hooks/open-telemetry/pkg/otel.go#L41-L44

**Comment by thisthat** [comment]
Thanks @Kavindu-Dodan for the answer. I have the feeling that we should invert the default behavior, i.e., by default not marking the request as erroneous. I think in the majority of cases, I don't want to mark a request failed because there was a problem in the FF evaluation, for the end user everything worked fine.

**Comment by Kavindu-Dodan** [comment]
@thisthat I have updated the PR to support the agreement. 

Plus, updated PR description & underlying issue for visibility. In summary, 

- Hooks will **NOT** set Span status to`Error` by default
- The end user will get an **option** (option name - `WithErrorStatusEnabled`) to configure the hook to set `Error` status for errors 

cc - @toddbaert @beeme1mr @bacherfl

**Review by thisthat — APPROVED** [review]

**Review by beeme1mr — APPROVED** [review]

**Pull request merged**
