### PR TITLE
fix(ofrep): close http response body after using it

### PR DESCRIPTION
**Pull request by erka**
## This PR

- This PR fixes the memory leak when using http client.
- It also cleanups few tests and typos.

### CODE REVIEW

**Review by beeme1mr — APPROVED** [review]

**Review by thomaspoignant — APPROVED** [review]
Good catch for closing the body.
And the cleanup makes sense to me.

**Comment by erka** [comment]
Hey @beeme1mr @thomaspoignant. Is there anything else preventing this PR from being merged?

**Comment by thomaspoignant** [comment]
@erka no nothing.
I'll merge it and release it.

**Comment by erka** [comment]
@thomaspoignant thank you!

**Comment by thomaspoignant** [comment]
It is released !

**Pull request merged**
