### PR TITLE
feat: Add Flipt Go Provider

### PR DESCRIPTION
**Pull request by markphelps**
## This PR

Ports over https://github.com/flipt-io/flipt-openfeature-provider-go to now live under this repository.

Our plan is to archive the provider at https://github.com/flipt-io/flipt-openfeature-provider-go and point users/documentation to this repository.

### Related Issues

Fixes #1234523

### Notes

I chose to start the version of the Flipt provider at 0.1.0 instead of continuing with the versioning of https://github.com/flipt-io/flipt-openfeature-provider-go as I've had to move around the packages a bit, which would break backward compatibility with imports

### CODE REVIEW

**Review by Kavindu-Dodan — APPROVED** [review]
Changes looks good from OpenFeature point of view.

I will update our CI to use latest stable Go version https://github.com/open-feature/go-sdk-contrib/pull/377  which should make the build green.

**Comment by Kavindu-Dodan** [comment]
@markphelps could you please update the branch to the latest main version ?

**Comment by markphelps** [comment]
Thanks @Kavindu-Dodan !!

**Comment by Kavindu-Dodan** [comment]
@markphelps  welcome & please see the initial release at https://github.com/open-feature/go-sdk-contrib/releases/tag/providers%2Fflipt%2Fv0.1.1

**Pull request merged**
