### PR TITLE
chore: Bump GO version

### PR DESCRIPTION
**Pull request by thomaspoignant**
## This PR
GO `1.19` is deprecated https://endoflife.date/go, this PR bumps the version to `1.21`.

### CODE REVIEW

**Comment by toddbaert** [comment]
@thomaspoignant should we also bump the min go versions in the project go-mods? Or is it common practice to keep them on lower (deprecated) versions.

We could increment them all to Go 1.20.

**Comment by Kavindu-Dodan** [comment]
I also had a similar idea proposed through this PR - https://github.com/open-feature/go-sdk-contrib/pull/377 

This is a blocker for Flipt provider PR - https://github.com/open-feature/go-sdk-contrib/pull/376

Per my knowledge, we can use any latest version of Go and each provider vendor can choose their version of choice for the minmum supported version through go.mod file. However, CI should support the latest stable version so vendors can stay at most recent version if they like.

**Comment by thomaspoignant** [comment]
@Kavindu-Dodan do you think I can remove this PR and we can merge yours instead?

**Comment by thomaspoignant** [comment]
Closing this one since the one from @Kavindu-Dodan has been merged

**Pull request closed without merging**
