### PR TITLE
refactor: migrate to connectrpc/connect-go

### PR DESCRIPTION
**Pull request by craigpastro**
## This PR

Migrate from bufbuild/connect-go to connectrpc/connect-go.

Part of https://github.com/open-feature/flagd/issues/790. Related to https://github.com/open-feature/flagd/pull/990.

There is some trouble with circular-ish dependencies though. This needs to be merged for the integration test in https://github.com/open-feature/flagd/pull/990 to pass, but this needs https://github.com/open-feature/flagd/pull/990 to be merged to compile. I tested locally with a `replace` statement and everything was fine.

This PR also cleans up imports and moves to go.uber.org/mock from github.com/golang/mock which is no longer maintained.

### CODE REVIEW

**Review by toddbaert — APPROVED** [review]

**Comment by Kavindu-Dodan** [comment]
I released upstream flagd. However, we need to perform two more steps before acepting this

1. Fix releases propsed through this PR - https://github.com/open-feature/go-sdk-contrib/pull/380
2. Release flagd testing and adopt latest flagd core release and testing release 

Then we will not have the test failure caused by multiple protobuf registrations

**Review by Kavindu-Dodan — CHANGES_REQUESTED** [review]
I have to block this till https://github.com/open-feature/go-sdk-contrib/pull/372#issuecomment-1809306620 is done. Otherwise thank you for taking care of this @craigpastro 🤝

**Comment by toddbaert** [comment]
@Kavindu-Dodan I did what you described [here](https://github.com/open-feature/go-sdk-contrib/pull/372#issuecomment-1809306620) (I also had to update the go version in the CI to 1.20 (1.19 is deprecated now) to fix a compilation issue. I think we may want to update all go.mods to use v1.20, but lets do that in a separate PR.

**Comment by Kavindu-Dodan** [comment]
> @Kavindu-Dodan I did what you described [here](https://github.com/open-feature/go-sdk-contrib/pull/372#issuecomment-1809306620) and tests are now passing. (I also had to update the go version in the CI to 1.20 (1.19 is deprecated now) to fix a compilation issue. I think we may want to update all go.mods to use v1.20, but lets do that in a separate PR.

Awesome, thanks for taking care of the dependency bump 🤝

**Review by Kavindu-Dodan — APPROVED** [review]
LGTM 🎉

**Comment by Kavindu-Dodan** [comment]
@craigpastro thank you again for the contribution :)

**Comment by craigpastro** [comment]
My pleasure!

**Pull request merged**
